#ifndef EEPROM_ADR_H
#define EEPROM_ADR_H

#define EA_DAC_GAIN_COMP_POS_VOL 0x00
#define EA_DAC_GAIN_COMP_NEG_VOL 0x04
#define EA_ADC_GAIN_COMP_POS_VOL 0x08
#define EA_ADC_GAIN_COMP_NEG_VOL 0x012

#define EA_DAC_GAIN_COMP_POS_CUR 0x016
#define EA_DAC_GAIN_COMP_NEG_CUR 0x020
#define EA_ADC_GAIN_COMP_POS_CUR 0x024
#define EA_ADC_GAIN_COMP_NEG_CUR 0x028

#define EA_DAC_ZERO_COMP_VOL 0x032
#define EA_DAC_ZERO_COMP_CUR 0x036



#define EA_ADC_NONLINEAR_COMP_NR 0x100
#define EA_ADC_NONLINEAR_COMP_START 0x0104



#endif EEPROM_ADR_H
