
#define KEYBOARD_1 1
#define KEYBOARD_2 2
#define KEYBOARD_3 3
#define KEYBOARD_4 4
#define KEYBOARD_5 5
#define KEYBOARD_6 6
#define KEYBOARD_7 7
#define KEYBOARD_8 8
#define KEYBOARD_9 9
#define KEYBOARD_0 10

#define KEYBOARD_COMMA 11
#define KEYBOARD_UV 12
#define KEYBOARD_MV 13
#define KEYBOARD_V 14
#define KEYBOARD_BACK 15
#define KEYBOARD_CLR 16

#define KEYBOARD_PLUSMINUS 17
#define KEYBOARD_DIVIDE10 18
#define KEYBOARD_TIMES10 19

#define KEYBOARD_PLUS_10MV 30
#define KEYBOARD_MINUS_10MV 31

#define KEYBOARD_OK 50
#define KEYBOARD_CANCEL 51


#define BUTTON_SOURCE_SET 100
#define BUTTON_LIM_SET 110
#define BUTTON_VOLT_AUTO 111
#define BUTTON_CUR_AUTO 112
#define BUTTON_CLEAR_BUFFER 113
#define BUTTON_NULL 114
#define BUTTON_UNCAL 115

#define TAG_FILTER_SLIDER_B 122
#define TAG_FILTER_SLIDER 123

#define MENU_BUTTON_SOURCE_PULSE 150

#define GESTURE_AREA_LOW 200
#define GESTURE_AREA_HIGH 201

#define MAIN_MENU_CLOSE 220
