
#define KEYBOARD_1 1
#define KEYBOARD_2 2
#define KEYBOARD_3 3
#define KEYBOARD_4 4
#define KEYBOARD_5 5
#define KEYBOARD_6 6
#define KEYBOARD_7 7
#define KEYBOARD_8 8
#define KEYBOARD_9 9
#define KEYBOARD_0 10

#define KEYBOARD_COMMA 11
#define KEYBOARD_UV 12
#define KEYBOARD_MV 13
#define KEYBOARD_V 14
#define KEYBOARD_BACK 15
#define KEYBOARD_CLR 16

#define KEYBOARD_PLUSMINUS 17
#define KEYBOARD_DIVIDE10 18
#define KEYBOARD_TIMES10 19

#define KEYBOARD_PLUS_10MV 30
#define KEYBOARD_MINUS_10MV 31

#define KEYBOARD_OK 50
#define KEYBOARD_CANCEL 51

#define BUTTON_ADC_GAIN_COMP_UP 60
#define BUTTON_ADC_GAIN_COMP_DOWN 61
#define BUTTON_DAC_GAIN_COMP_UP 62
#define BUTTON_DAC_GAIN_COMP_DOWN 63
#define BUTTON_DAC_GAIN_COMP_UP2 64
#define BUTTON_DAC_GAIN_COMP_DOWN2 65

#define BUTTON_ADC_GAIN_COMP_UP2 66
#define BUTTON_ADC_GAIN_COMP_DOWN2 67

#define BUTTON_DAC_GAIN_COMP_LIM_UP 68
#define BUTTON_DAC_GAIN_COMP_LIM_DOWN 69

#define BUTTON_DAC_ZERO_COMP_UP 70
#define BUTTON_DAC_ZERO_COMP_DOWN 71

#define BUTTON_SOURCE_SET 100
#define BUTTON_LIM_SET 110
#define BUTTON_VOLT_AUTO 111
#define BUTTON_CUR_AUTO 112
#define BUTTON_CLEAR_BUFFER 113
#define BUTTON_REL 114
#define BUTTON_UNCAL 115
#define BUTTON_DAC_NONLINEAR_CALIBRATE 116
#define BUTTON_DAC_ZERO_CALIBRATE 117

#define TAG_FILTER_SLIDER_B 122
#define TAG_FILTER_SLIDER 123

#define BUTTON_SAMPLE_RATE_5 160
#define BUTTON_SAMPLE_RATE_20 161
#define BUTTON_SAMPLE_RATE_50 162
#define BUTTON_SAMPLE_RATE_100 163

#define MENU_BUTTON_SOURCE_PULSE 180
#define MENU_BUTTON_SOURCE_DC_VOLTAGE 181
#define MENU_BUTTON_SOURCE_DC_CURRENT 182
#define MENU_BUTTON_SOURCE_SWEEP 183
#define MENU_BUTTON_DIGITIZE 184
#define MENU_BUTTON_GRAPH 185

#define PULSE_BUTTON_INC 190
#define PULSE_BUTTON_DEC 191
#define PULSE_BUTTON_INC2 193
#define PULSE_BUTTON_DEC2 194
#define PULSE_BUTTON_INC3 195
#define PULSE_BUTTON_DEC3 196

#define SWEEP_BUTTON_INC 200
#define SWEEP_BUTTON_DEC 201
#define SWEEP_BUTTON_STEP_INC 202
#define SWEEP_BUTTON_STEP_DEC 203
#define SWEEP_BUTTON_VOLT_INC 204
#define SWEEP_BUTTON_VOLT_DEC 205
#define SWEEP_BUTTON_CLEAR 206

/*
#define GESTURE_AREA_LOW 240
#define GESTURE_AREA_HIGH 241
*/

#define MAIN_MENU_CLOSE 250
